version: '3.8'
services:
  pricing-api:
    build: ./pricing-api
    ports:
      - "5000:5000"
    env_file:
      - ./pricing-api/.env
  product-api:
    build: ./product-api
    ports:
      - "8001:8001"
    env_file:
      - ./product-api/.env
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - product-api
      - pricing-api
