pipeline:
  identifier: Build_Daveu1983_kube_shop_1744302128409
  name: Build kube-shop
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1744302082715
        repoName: Daveu1983/kube-shop
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npm_install
                  name: Install Frontend Dependencies
                  spec:
                    command: |
                      cd frontend
                      npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
