apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: kube-shop
    includeSelectors: true

resources:
  - pricing-api-deployment.yaml
  - pricing-api-service.yaml
  - product-api-deployment.yaml
  - product-api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

images:
  - name: pricing-api
    newTag: local
  - name: product-api
    newTag: local
  - name: frontend
    newTag: local
